name: Update Download Counts

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0 * * *'  # Runs daily at 00:01

permissions:
  actions: 'read'
  contents: 'write'

jobs:
  update-download-counts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate timestamp
      run: echo "BUILD_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Run download counts script
      run: python get-download-counts-from-galaxy.py --fetch

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Configuring git..."
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        echo "Adding changes to git..."
        git add . -u
        git commit -m "Update download counts" -m "Generated by GitHub Actions"
        echo "Pushing changes to GitHub..."
        git push origin main
